version: "3"
services:
    backend:
        container_name: node_app
        environment:
            HOME_DRIVE_PATH: /usr/src/app/storage
        ports:
            - 8000:8000
    frontend:
        container_name: react_app
        ports:
            - 3000:3000
        depends_on:
            - backend
